# -*- mode: ruby -*-

project_title = "{project_title}"
project_ip = "{project_ip}"
project_hostname = "{project_hostname}"
project_mountpoint = "{project_mountpoint}"
project_dbname = "{project_dbname}"
project_dbpass = "{project_dbpass}"


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  # install plugin to set disk size on build
  # vagrant plugin install vagrant-disksize
  config.disksize.size = '50GB'

  config.vm.provision :shell,
    path: "./boss",
    args: [
      "install",
      project_hostname,
      "phpmyadmin",
      "cert",
      "lamp",
      "composer",
      "virtualhost",
      "craft3",
      "fakesmtp",
      "--db-name=" + project_dbname,
      "--db-root-pass=" + project_dbpass,
      "--site-name-and-root=" + project_hostname + ",public_html,n",
    ]
  # If you don't want to use the provisioner, run this command inside the vm instead.
  #
  # /project/boss install {project_hostname} phpmyadmin cert lamp composer virtualhost craft3 fakesmtp --db-name={project_dbname} --site-name-and-root={project_hostname},public_html,n -d

  config.vm.define project_title do |sink| end

  config.vm.network "private_network", ip: project_ip
  config.vm.hostname = project_hostname

  config.vm.synced_folder ".", "/project"
  config.vm.synced_folder project_mountpoint, "/var/www",
                          group: "www-data", owner: "www-data"

  # config.vm.synced_folder "server/public_html", "/var/www/public_html",
  #                         group: "www-data", owner: "www-data"
  # config.vm.synced_folder "server/private_html", "/var/www/private_html",
  #                         group: "www-data", owner: "www-data"

  config.vm.provider :virtualbox do |vb|
    # https://stackoverflow.com/q/28323953/2177602
    # https://stackoverflow.com/a/18457420/2177602
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.cpus = 4
    vb.memory = 8192 # default 1024
  end
end
